# Global 全局配置
site_analytics: ''
hoster: <a href="https://systemannounce.github.io">Github Pages</a>  &  <a href="https://systemannounce.netlify.app">Netlify</a>  &  <a href="https://cloud.tencent.com/">tencentcloud</a>
site_logo: '/images/ico.jpg'  #网站的LOGO图片文件，请注意与后面核心JS的设置保持一致。
snow: true
click_animate_js: 'candy'
enable_dark: true
highlight_theme: night-eighties # 代码高亮主题（light | night | night-eighties | night-blue | night-bright）
check_update: true
# canonical: true

vendors:
  packages:
    disqusjs: 
      version: 1.2.6
    gitalk: 
      version: 1.7.2
    gitment: 
      version: 0.0.3
    twikoo: 
      version: 1.5.11
    valine: 
      version: 1.4.18
    "@waline/client": 
      version: 2.14.1
    bootstrap: 
      version: 3.3.4
    nprogress: 
      version: 0.2.0
    aplayer: 
      version: 1.10.1
    "@fancyapps/fancybox": 
      version: 3.5.7
    layui-src: 
      version: 2.5.5
    font-awesome: 
      version: 4.7.0
    jquery: 
      version: 3.6.0
    qrcode_js: 
      version: 1.0.0
    mermaid: 
      version: 9.1.1
    meting:
      version: 2.0.1

# 自定义样式
customStyles:
  images: # 图片相关设置
    # banner: /images/1662289092353.jpg # 站点横幅
    # background: /images/bg.webp # 站点背景

# Index 首页配置
index:
  post_type: false
  read_count: true
  comment_count: true

# Top Menu 顶部导航栏配置 （具体格式请参照文档）
# menu:
#   index: /
#   archives: /archives/
#   friends: /friends/
#   sites:
#     submenu: true
#     author: https://candinya.com
#     project: https://github.com/Candinya/Kratos-Rebirth

# label:
#   index: <i class="fa fa-home"></i>首页
#   archives: <i class="fa fa-file"></i>档案馆
#   friends: <i class="fa fa-paw"></i>好伙伴
#   sites:
#     submenu: <i class="fa fa-link"></i>链接
#     author: 作者博客
#     project: 项目链接

topMenu:
  - label: 首页
    icon: home
    url: /
  - label: 伊斯特瓦尔
    icon: file
    submenu:
      - label: 总览
        icon: book
        url: /archives/
      - label: 搜索
        icon: search
        url: /search
      - label: 游戏生涯记录
        icon: gamepad
        url: /2023/05/25/record/gamerecord/
      - label: 番剧生涯记录
        icon: tv
        url: /2023/05/25/record/animerecord/
  - label: 友链
    icon: users
    url: /friends/
  - label: 关于我
    icon: paper-plane-o
    url: /2023/05/10/info/AboutME/
  - label: 外链
    icon: link
    submenu:
      - label: GitHub
        icon: github
        url: https://github.com/systemannounce
      - label: 网抑云
        icon: music
        url: https://music.163.com/#/user/home?id=512603380
      - label: Steam
        icon: steam
        url: https://steamcommunity.com/id/systemannouncement
      - label: bilibili
        icon: youtube-play
        url: https://space.bilibili.com/200704172
      - label: BGM
        icon: mixcloud
        url: https://bangumi.tv/user/systemannounce
  - label: RSS订阅
    icon: rss
    url: /rss2.xml





# Footer 页脚配置
group_link: #'https://space.bilibili.com/200704172'
contact: # 出于兼容性考虑，继续保留
  weibo: 
  mail: 'systemannounce@outlook.com'
  telegram: 'systemannounce'
  facebook: 'systemannounce'
  twitter: 'systemannounce'
  linkedin: 
  fediverse:
    instance:
    username:
  github: 'systemannounce'
  rss: 'rss2.xml'
footerLinks: [] # 可以自定义
timenotice: 本站已运行
icp: 
 - 粤ICP备2023055552号-1
 - <a href="https://icp.gov.moe/?keyword=20231634" target="_blank">萌ICP备20231634号</a>
psr: 
  
# Post Page 文章页配置       comments setting
posts:
  show_cc: false
  donate: false
  share: true
  comments: 
    provider: 'disqus'
    enableBGImage: true
  wordCount: 
    enable: true
    threshold: 3000

# Disqus [Disqus](https://disqus.com) 评论相关
disqus:
  shortname: felixsana

# DisqusJS [DisqusJS](https://disqusjs.skk.moe/) 评论相关
disqusjs:
  shortname: 
  sitename: 
  api: 
  apikey: 
  admin: 
  adminlabel: 

# Valine [Valine](https://valine.js.org) 评论相关
valine:
  app_id: 'wcAY073UtTmL3vpozysjm8WW-gzGzoHsz'
  app_key: 'an7fOYS8Ktba756cqHCF3kww'
  visitor: true
  enableQQ: true

# Twikoo [Twikoo](https://twikoo.js.org) 评论相关
twikoo:
  env_id: https://twikoo-comment-nu.vercel.app/

# Waline [Waline](https://waline.js.org) 评论相关
## 不仅限于以下内容，您可以参照 Waline的 [前端配置文档](https://waline.js.org/reference/client.html) 设置您需要的配置项
## el 和 path 会在页面自动生成，不必加入
#   需要梯子进行访问！！！！！
waline:
  serverURL: https://blogvercel-two.vercel.app/
  comment: true
  pageview: true

# Gitalk [Gitalk](https://gitalk.github.io/) 评论相关
## 不仅限于以下内容，您可以参照 [Gitalk 文档](https://github.com/gitalk/gitalk/blob/master/readme-cn.md#%E8%AE%BE%E7%BD%AE) 设置您需要的配置项
## id 会在页面自动生成，不必加入
gitalk:
  clientID: 'GitHub Application Client ID'
  clientSecret: 'GitHub Application Client Secret'
  repo: 'Kratos-Rebirth-Demo'
  owner: 'Candinya'
  admin: 
    - 'Candinya'
  distractionFreeMode: false

# Gitment [Gitment](https://github.com/imsun/gitment/) 评论相关
## 不仅限于以下内容，您可以参照 [Gitment 文档](https://github.com/imsun/gitment#methods) 设置您需要的配置项
## id 会在页面自动生成，不必加入
gitment:
  owner: 'Candinya'
  repo: 'Kratos-Rebirth-Demo'
  oauth:
    client_id: 'Your client ID'
    client_secret: 'Your client secret'

# LiveRe [LiveRe](https://livere.com/) 评论相关
livere:
  id: city
  uid: MTAyMC81ODQ3MS8zNDkzNA==

# APlayer 左下角音乐播放器
aplayer:
  enabled: true
  playlist: 
  meting:
    server: netease
    type: playlist
    id: 8410660170
  order: random

# Widgets 侧边栏小挂件
sidebar: right
widgets:
- about
- splitter
- toc
- category
- tagcloud
- posts
avatarUri: /images/66364037_p0.png
mobile_toc: 
  hide: false
  hide_id: false

# Fancybox 文章内图片单击放大
fancybox: true

# Search 搜索
search:
  enable: true
  path: search.json
  field: post # page | post | all. Default post
  content: true # Include post | page content

# JavaScript 相关配置
## 由于Javascript被压缩后难以有效编辑与生成，因而为了简化操作，将相关的配置项在生成文件时以独立的json文件写出，调用时使用fetch API获取。
jsconfig:
  main:
    cover:
      randomAmount: 20 # 表示从1~20 无文章图片时使用随机图片的范围
      baseUrl: null # 使用默认值（不单独配置），将跟随 vendors 中的相关设定选择是否使用 cdn “基础图片基础路径”
      filenameTemplate: "thumb_{no}.webp" # no 指的是编号
    createTime: "2023/05/09 22:39:28"
    donateBtn: "支持我~"
    scanNotice: "扫一扫，好不好？"
    qr_alipay: "/images/alipayqr.webp"
    qr_wechat: "/images/wechatpayqr.webp"
    siteLeaveEvent: true
    leaveTitle: "{{{(>_<)}}}哦哟，崩溃啦~"
    returnTitle: "(*´∇｀*)欸，又好啦~"
    copyrightNotice: "该内容采用 CC BY-NC-SA 4.0 许可协议，著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处。"
    expire_day: 365
    topNavScrollToggle: true

# Site verify 站点验证相关配置内容
site_verify:
  google: 
  baidu: codeva-yy6Ea5pHMl
  bing: 

# Friends 友链相关内容
friends:
  href: "friends"
  page:
    title: 大家都是朋友
    comments: true
    description: "静候来访"
    updated: "2023-05-11"
  list:
  - name: "猫猫可爱的呢"
    bio: "喵~"
    avatar: "../images/93331597_p0.png"
    link: "https://nya.one/@systemannounce"
  verify: false # 验证每个友链的可访问性，炸了会有提示

# Misc 杂项
misc:
  showWordCountEstimateWavy: true # 在文章字数处显示表示大约字数的波浪号
